// ==========================================================================
// Catálogo de libros — ÚNICA fuente de datos de producto para toda la web.
// Se usa en: categoria.html (listado/filtros/buscador), producto.html
// (ficha dinámica) e index.html (destacados).
//
// Para añadir un libro nuevo: copia un objeto, cambia el "id" (debe ser
// único, sin espacios) y rellena sus campos. No hace falta tocar más
// archivos: aparecerá solo en el catálogo, en el buscador y en su propia
// ficha de producto (producto.html?id=tu-id).
// ==========================================================================

// Devuelve la ruta .webp de una portada (mismo nombre, sin la extensión
// .jpg). Todas las portadas tienen ya su copia .webp generada en /img
// (más ligera). Si por lo que sea faltara esa copia, el atributo
// onerror="" de cada <img> hace que el navegador recupere el .jpg original
// automáticamente, así que esto nunca puede dejar una portada rota.
window.toWebp = function (coverPath) {
  return coverPath.replace(/\.jpg$/i, '.webp');
};

window.BOOKS = [
  {
    id: 'el-conflicto-de-los-siglos',
    title: 'El Conflicto de los Siglos',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 19.54,
    format: 'Tapa dura',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/el-conflicto-de-los-siglos.jpg',
    badge: null,
    description: 'Un recorrido por la gran lucha entre el bien y el mal a través de la historia, desde la destrucción de Jerusalén hasta la restauración final de la tierra. Un clásico de la literatura devocional adventista, con un lenguaje claro pensado tanto para el estudio personal como para el regalo.',
    idioma: 'Español'
  },
  {
    id: 'el-deseado-de-todas-las-gentes',
    title: 'El Deseado de Todas las Gentes',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 14.20,
    format: 'Tapa blanda, A5',
    formatSlug: 'rustica',
    priceNote: 'Envío incluido',
    cover: 'img/el-deseado-de-todas-las-gentes.jpg',
    badge: null,
    description: 'Una mirada cercana a la vida de Jesús, desde su nacimiento hasta su ascensión, que combina el relato bíblico con reflexiones devocionales. Uno de los libros más leídos de Elena G. White, en una edición manejable en tapa blanda tamaño A5.',
    idioma: 'Español'
  },
  {
    id: 'historia-de-los-patriarcas-y-profetas',
    title: 'Historia de los Patriarcas y Profetas',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 26.20,
    format: 'Edición tapa dura',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/historia-de-los-patriarcas-y-profetas.jpg',
    badge: null,
    description: 'Repasa los grandes relatos del Antiguo Testamento, desde la creación hasta el rey David, iluminando el carácter de Dios a través de la vida de los patriarcas y los primeros profetas. Edición en tapa dura, pensada para durar en tu biblioteca.',
    idioma: 'Español'
  },
  {
    id: 'profetas-y-reyes',
    title: 'Profetas y Reyes',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 11.83,
    format: 'Edición tapa blanda',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/profetas-y-reyes.jpg',
    badge: 'Nuevo',
    description: 'Continúa el relato bíblico a través de los reinos de Israel y Judá, la obra de Elías, Eliseo, Isaías y los profetas mayores, hasta el regreso del cautiverio babilónico. Una edición cuidada en tapa blanda, ideal para el estudio diario.',
    idioma: 'Español'
  },
  {
    id: 'la-fe-por-la-cual-vivo',
    title: 'La Fe por la Cual Vivo',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.14,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/la-fe-por-la-cual-vivo.jpg',
    badge: null,
    description: 'Un repaso claro y ordenado de las creencias fundamentales que sostienen la fe cristiana, escrito para fortalecer la confianza del lector en las promesas de Dios. Ideal como libro de estudio personal o para compartir con quien empieza a explorar la fe.',
    idioma: 'Español'
  },
  {
    id: 'la-educacion',
    title: 'La Educación',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 8.05,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/la-educacion.jpg',
    badge: null,
    description: 'Un clásico sobre el propósito real de la enseñanza: formar el carácter, no solo llenar la mente de datos. Plantea un modelo educativo que integra mente, cuerpo y espíritu, con ideas tan vigentes hoy como cuando se escribieron.',
    idioma: 'Español'
  },
  {
    id: 'edificacion-del-caracter',
    title: 'Edificación del Carácter',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 6.52,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/edificacion-del-caracter.jpg',
    badge: null,
    description: 'Una guía práctica para crecer, paso a paso, en las virtudes cristianas: fe, virtud, conocimiento, templanza, paciencia, piedad, amor fraternal y caridad. Cada capítulo invita a examinar la propia vida y avanzar hacia un carácter más firme.',
    idioma: 'Español'
  },
  {
    id: 'hijos-e-hijas-de-dios',
    title: 'Hijos e Hijas de Dios',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.21,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/hijos-e-hijas-de-dios.jpg',
    badge: null,
    description: 'Una colección de meditaciones breves sobre la identidad del creyente como hijo de Dios, pensada para el devocional diario. Anima a vivir con la seguridad de quien sabe a quién pertenece.',
    idioma: 'Español'
  },
  {
    id: 'exaltad-a-jesus',
    title: 'Exaltad a Jesús',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.22,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/exaltad-a-jesus.jpg',
    badge: null,
    description: 'Un devocional centrado por completo en la persona de Cristo: su carácter, su amor y su obra de salvación. Cada lectura busca acercar al lector a una relación más cercana con Jesús.',
    idioma: 'Español'
  },
  {
    id: 'en-los-lugares-celestiales',
    title: 'En los Lugares Celestiales',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.12,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/en-los-lugares-celestiales.jpg',
    badge: null,
    description: 'Meditaciones diarias inspiradas en la idea de que el creyente ya vive, en cierto sentido, en comunión con el cielo. Un libro pensado para empezar el día con una mirada puesta en lo eterno.',
    idioma: 'Español'
  },
  {
    id: 'fe-y-obras',
    title: 'Fe y Obras',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 6.75,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/fe-y-obras.jpg',
    badge: null,
    description: 'Explora la relación entre la fe que salva y las obras que la acompañan, un tema clásico del cristianismo. Ayuda a entender que una fe viva se traduce siempre en una vida transformada.',
    idioma: 'Español'
  },
  {
    id: 'el-otro-poder',
    title: 'El Otro Poder',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 7.03,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/el-otro-poder.jpg',
    badge: null,
    description: 'Reflexiona sobre el poder del amor, el hogar y la influencia personal frente a otras formas de poder más visibles. Un libro sobre cómo las decisiones cotidianas moldean el carácter y la familia.',
    idioma: 'Español'
  },
  {
    id: 'el-ministerio-pastoral',
    title: 'El Ministerio Pastoral',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 8.57,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/el-ministerio-pastoral.jpg',
    badge: null,
    description: 'Dirigido a pastores y líderes de iglesia, reúne consejos prácticos sobre el cuidado de la congregación, la predicación y el ejemplo personal. Un manual de referencia para quienes ejercen el ministerio.',
    idioma: 'Español'
  },
  {
    id: 'el-deseado-de-todas-las-gentes-tapa-blanda',
    title: 'El Deseado de Todas las Gentes',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 10.32,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/el-deseado-de-todas-las-gentes-tapa-blanda.jpg',
    badge: null,
    description: 'Una mirada cercana a la vida de Jesús, desde su nacimiento hasta su ascensión, que combina el relato bíblico con reflexiones devocionales. Uno de los libros más leídos de Elena G. White, en esta edición en tapa blanda.',
    idioma: 'Español'
  },
  {
    id: 'el-ministerio-de-publicaciones',
    title: 'El Ministerio de Publicaciones',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.14,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/el-ministerio-de-publicaciones.jpg',
    badge: null,
    description: 'Reúne consejos sobre la obra de impresión y distribución de literatura cristiana, un pilar histórico de la difusión del mensaje adventista. De interés especial para quienes trabajan en editoriales o en la venta de libros religiosos.',
    idioma: 'Español'
  },
  {
    id: 'el-ministerio-de-la-bondad',
    title: 'El Ministerio de la Bondad',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 8.23,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/el-ministerio-de-la-bondad.jpg',
    badge: null,
    description: 'Un llamado a vivir el evangelio a través de actos concretos de bondad y ayuda al necesitado. Muestra cómo la compasión práctica abre puertas que la sola predicación no siempre alcanza.',
    idioma: 'Español'
  },
  {
    id: 'el-ministerio-medico',
    title: 'El Ministerio Médico',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 10.94,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/el-ministerio-medico.jpg',
    badge: null,
    description: 'Aborda la relación entre la salud física y la obra evangélica, con consejos sobre el cuidado del cuerpo como parte del mensaje cristiano integral. Un referente para quienes trabajan en el área de la salud desde la fe.',
    idioma: 'Español'
  },
  {
    id: 'el-hogar-cristiano',
    title: 'El Hogar Cristiano',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.68,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/el-hogar-cristiano.jpg',
    badge: null,
    description: 'Un manual clásico sobre la vida familiar: el matrimonio, la crianza de los hijos y la atmósfera espiritual del hogar. Sigue siendo, décadas después, una de las obras más consultadas sobre la familia cristiana.',
    idioma: 'Español'
  },
  {
    id: 'el-evangelismo',
    title: 'El Evangelismo',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 10.76,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/el-evangelismo.jpg',
    badge: null,
    description: 'Reúne principios y métodos para compartir la fe de forma eficaz, con énfasis en el amor y el respeto hacia quien escucha el mensaje. Un recurso práctico para quienes participan en la obra misionera de la iglesia.',
    idioma: 'Español'
  },
  {
    id: 'el-conflicto-inminente',
    title: 'El Conflicto Inminente',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 6.84,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/el-conflicto-inminente.jpg',
    badge: null,
    description: 'Analiza los grandes acontecimientos finales descritos en la profecía bíblica y su relevancia para la vida cristiana actual. Un libro de estudio para quienes se interesan por la escatología bíblica.',
    idioma: 'Español'
  },
  {
    id: 'el-colportor-evangelico',
    title: 'El Colportor Evangélico',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 7.49,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/el-colportor-evangelico.jpg',
    badge: null,
    description: 'Dirigido a quienes se dedican a la venta y distribución de literatura cristiana puerta a puerta, con consejos prácticos y motivación espiritual para esa labor. Un clásico dentro de la tradición del colportaje.',
    idioma: 'Español'
  },
  {
    id: 'dios-nos-cuida',
    title: 'Dios Nos Cuida',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.31,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/dios-nos-cuida.jpg',
    badge: null,
    description: 'Un devocional matutino breve, pensado para leer cada mañana y empezar el día recordando el cuidado providencial de Dios. Fácil de intercalar en cualquier rutina, aunque sea apretada.',
    idioma: 'Español'
  },
  {
    id: 'de-la-ciudad-al-campo',
    title: 'De la Ciudad al Campo',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 6.63,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/de-la-ciudad-al-campo.jpg',
    badge: null,
    description: 'Reflexiona sobre las ventajas de la vida sencilla en contacto con la naturaleza frente al ritmo agitado de la ciudad. Un libro que invita a repensar el estilo de vida desde una perspectiva cristiana.',
    idioma: 'Español'
  },
  {
    id: 'la-pasion-del-amor',
    title: 'La Pasión del Amor',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 8.01,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/la-pasion-del-amor.jpg',
    badge: null,
    description: 'Una meditación sobre el amor de Dios manifestado en la cruz, y lo que ese amor significa para la vida diaria del creyente. Un libro breve pensado para la reflexión personal.',
    idioma: 'Español'
  },
  {
    id: 'cristo-nuestro-salvador',
    title: 'Cristo Nuestro Salvador',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 6.93,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/cristo-nuestro-salvador.jpg',
    badge: null,
    description: 'Una introducción sencilla y accesible a la vida y la obra de Jesús, pensada tanto para nuevos creyentes como para quienes desean repasar lo esencial del evangelio. Ideal como primer libro de estudio sobre la persona de Cristo.',
    idioma: 'Español'
  },
  {
    id: 'cristo-en-su-santuario',
    title: 'Cristo en Su Santuario',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 6.93,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/cristo-en-su-santuario.jpg',
    badge: null,
    description: 'Explica el simbolismo del santuario bíblico y su cumplimiento en la obra de Cristo, un tema central de la teología adventista. Un libro de estudio para profundizar en la doctrina del santuario.',
    idioma: 'Español'
  },
  {
    id: 'el-deseado-de-todas-las-gentes-tapa-dura',
    title: 'El Deseado de Todas las Gentes',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 17.58,
    format: 'Tapa dura, 155 x 235 mm',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/el-deseado-de-todas-las-gentes-tapa-dura.jpg',
    badge: null,
    description: 'Una mirada cercana a la vida de Jesús, desde su nacimiento hasta su ascensión, que combina el relato bíblico con reflexiones devocionales. Esta edición en tapa dura, de mayor formato, está pensada para quienes buscan un ejemplar más duradero o para regalo.',
    idioma: 'Español'
  },
  {
    id: 'consejos-sobre-la-mayordomia-cristiana',
    title: 'Consejos sobre la Mayordomía Cristiana',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 8.51,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/consejos-sobre-la-mayordomia-cristiana.jpg',
    badge: null,
    description: 'Reúne principios sobre el uso responsable del tiempo, el dinero y los talentos como parte de la vida de fe. Plantea la mayordomía no como obligación, sino como una forma de vivir con propósito.',
    idioma: 'Español'
  },
  {
    id: 'consejos-sobre-la-obra-de-escuela-sabatica',
    title: 'Consejos sobre la Obra de Escuela Sabática',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 7.69,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/consejos-sobre-la-obra-de-escuela-sabatica.jpg',
    badge: null,
    description: 'Dirigido a maestros y líderes de Escuela Sabática, ofrece orientación práctica para enseñar la Biblia de forma clara y relevante a todas las edades. Un recurso de referencia para quienes sirven en esa área de la iglesia.',
    idioma: 'Español'
  },
  {
    id: 'consejos-para-los-maestros',
    title: 'Consejos para los Maestros',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.65,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/consejos-para-los-maestros.jpg',
    badge: null,
    description: 'Consejos prácticos sobre la vocación docente desde una perspectiva cristiana, con énfasis en la formación del carácter tanto como del intelecto. Útil para educadores en escuelas de la iglesia y también para padres.',
    idioma: 'Español'
  },
  {
    id: 'consejos-para-la-iglesia',
    title: 'Consejos para la Iglesia',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.96,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/consejos-para-la-iglesia.jpg',
    badge: null,
    description: 'Una recopilación de consejos sobre la vida y la organización de la congregación local, pensada para líderes y miembros comprometidos con la salud espiritual de su iglesia.',
    idioma: 'Español'
  },
  {
    id: 'conflicto-y-valor',
    title: 'Conflicto y Valor',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.15,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/conflicto-y-valor.jpg',
    badge: null,
    description: 'Un devocional diario que combina textos bíblicos y meditaciones breves sobre la lucha entre el bien y el mal en la vida cristiana. Pensado para fortalecer la fe día a día.',
    idioma: 'Español'
  },
  {
    id: 'cada-dia-con-dios',
    title: 'Cada Día con Dios',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.13,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/cada-dia-con-dios.jpg',
    badge: null,
    description: 'Un devocional diario, con una lectura breve para cada mañana del año, pensado para acompañar el tiempo personal de oración y estudio.',
    idioma: 'Español'
  },
  {
    id: 'creencias-de-los-adventistas-del-septimo-dia',
    title: 'Creencias de los Adventistas del Séptimo Día',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.52,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/creencias-de-los-adventistas-del-septimo-dia.jpg',
    badge: null,
    description: 'Una exposición clara de las doctrinas fundamentales de la Iglesia Adventista del Séptimo Día, pensada tanto para miembros como para quienes se acercan por primera vez a estas creencias.',
    idioma: 'Español'
  },
  {
    id: 'alza-tus-ojos',
    title: 'Alza Tus Ojos',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.12,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/alza-tus-ojos.jpg',
    badge: null,
    description: 'Un devocional que invita a mirar más allá de las circunstancias diarias hacia la esperanza cristiana, con lecturas breves pensadas para el ánimo y la reflexión.',
    idioma: 'Español'
  },
  {
    id: 'a-fin-de-conocerle',
    title: 'A Fin de Conocerle',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.20,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/a-fin-de-conocerle.jpg',
    badge: null,
    description: 'Un devocional centrado en el deseo de conocer más profundamente el carácter de Cristo a través de la lectura diaria y la meditación.',
    idioma: 'Español'
  },
  {
    id: 'review-and-herald',
    title: 'Review and Herald',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 15.74,
    format: 'Tapa dura, 155 x 235 mm',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/review-and-herald.jpg',
    badge: null,
    description: 'Una recopilación de artículos publicados originalmente en la histórica revista adventista Review and Herald, con reflexiones sobre la fe, la iglesia y la misión. Edición en tapa dura de gran formato.',
    idioma: 'Español'
  },
  {
    id: 'la-verdad-acerca-de-los-angeles',
    title: 'La Verdad Acerca de los Ángeles',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 7.90,
    format: 'Tapa blanda, 155 x 235 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/la-verdad-acerca-de-los-angeles.jpg',
    badge: null,
    description: 'Reúne lo que la Biblia y los escritos de la autora enseñan sobre la existencia y la obra de los ángeles, su papel en la historia bíblica y en la vida del creyente hoy.',
    idioma: 'Español'
  },
  {
    id: 'consejos-sobre-la-salud',
    title: 'Consejos sobre la Salud',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 11.64,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/consejos-sobre-la-salud.jpg',
    badge: null,
    description: 'Un compendio de principios sobre alimentación, ejercicio y estilo de vida saludable, entendidos como parte integral del bienestar espiritual. Sigue siendo una referencia dentro de la reforma pro salud adventista.',
    idioma: 'Español'
  },

// ---- Nuevos libros de Elena G. White (añadidos) ----
  {
    id: 'la-historia-de-la-redencion',
    title: 'La Historia de la Redención',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.86,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Un recorrido por el gran plan de salvación desde la caída hasta la restauración final, contado como una sola historia continua. Edición en tapa blanda con acabado brillo, pensada para el estudio personal y para regalar.',
    idioma: 'Español',
  },
  {
    id: 'la-iglesia-remanente',
    title: 'La Iglesia Remanente',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 6.48,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Una reflexión sobre la identidad y la misión del pueblo de Dios en el tiempo del fin, a partir de los escritos de la autora. Edición en tapa blanda con acabado brillo, ideal para el estudio personal.',
    idioma: 'Español',
  },
  {
    id: 'la-maravillosa-gracia-de-dios',
    title: 'La Maravillosa Gracia de Dios',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 9.15,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Un compendio devocional sobre la gracia de Dios y su obra en la vida del creyente, con lecturas breves pensadas para acompañar el día a día. Edición en tapa blanda con acabado brillo.',
    idioma: 'Español',
  },
  {
    id: 'la-musica',
    title: 'La Música',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 6.44,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Una recopilación de los escritos de la autora sobre el lugar de la música en el culto y en la vida cristiana. Edición en tapa blanda con acabado brillo, cuidada y de fácil lectura.',
    idioma: 'Español',
  },
  {
    id: 'la-oracion',
    title: 'La Oración',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 8.7,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Un devocional que reúne enseñanzas sobre la vida de oración, pensado para fortalecer la comunión diaria con Dios. Edición en tapa blanda con acabado brillo.',
    idioma: 'Español',
  },
  {
    id: 'la-segunda-venida-y-el-cielo',
    title: 'La Segunda Venida y el Cielo',
    author: 'Elena G. White',
    authorSlug: 'elena-g-white',
    category: 'elena-white',
    categoryLabel: 'Elena G. White',
    price: 7.05,
    format: 'Tapa blanda, 148 x 210 mm',
    formatSlug: 'rustica',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Una mirada esperanzadora a las promesas bíblicas sobre el regreso de Cristo y la vida eterna, explicadas con un lenguaje claro y devocional. Edición en tapa blanda con acabado brillo.',
    idioma: 'Español',
  },

// ---- Biblias ----
  {
    id: 'biblia-bilingue-rvr-nkjv-marron',
    title: 'Biblia Bilingüe RVR/NKJV, Marrón',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 38.99,
    format: 'Tapa dura entelada, dos tonos',
    formatSlug: 'tapa-dura',
    priceNote: 'Envío incluido',
    cover: 'img/biblia-bilingue-rvr-nkjv-marron.jpg',
    badge: 'Nuevo',
    description: 'Biblia bilingüe con el texto de la Reina Valera Revisada y la New King James Version en columnas, cubierta en dos tonos de marrón. Pensada tanto para el estudio comparado como para practicar inglés junto a la lectura bíblica.',
    idioma: 'Español',
    freeShipping: true,
  },
  {
    id: 'biblia-compacta-fucsia-floral-cierre',
    title: 'Biblia Compacta Letra Grande, Fucsia Floral con Cremallera',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 27.99,
    format: 'Tapa blanda, cierre de cremallera',
    formatSlug: 'tapa-dura',
    priceNote: 'Envío incluido',
    cover: 'img/biblia-compacta-fucsia-floral-cierre.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960 en formato compacto y letra grande (11 puntos), con cubierta floral en tono fucsia, cremallera e índice lateral. Ideal para llevar cada día.',
    idioma: 'Español',
    freeShipping: true,
  },
  {
    id: 'biblia-apuntes-rosa-floreada',
    title: 'Biblia de Apuntes Tapa Dura Entelada, Rosa Floreada',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 38.99,
    format: 'Tapa dura entelada, con banda elástica',
    formatSlug: 'tapa-dura',
    priceNote: 'Envío incluido',
    cover: 'img/biblia-apuntes-rosa-floreada.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, letra de 8,5 puntos, en edición de apuntes: márgenes amplios para anotar, cubierta entelada floral en tono rosa y cierre con banda elástica.',
    idioma: 'Español',
    freeShipping: true,
  },
  {
    id: 'biblia-apuntes-negro',
    title: 'Biblia de Apuntes Tapa Dura, Negro',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 38.04,
    format: 'Tapa dura, con banda elástica',
    formatSlug: 'tapa-dura',
    priceNote: 'Envío incluido',
    cover: 'img/biblia-apuntes-negro.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, letra de 8,5 puntos, en edición de apuntes: márgenes amplios para anotar, cubierta lisa en negro y cierre con banda elástica.',
    idioma: 'Español',
    freeShipping: true,
  },
  {
    id: 'biblia-apuntes-negro-oro',
    title: 'Biblia de Apuntes Tapa Dura, Negro/Oro',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 35.2,
    format: 'Tapa dura',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de apuntes con márgenes amplios para anotar, cubierta en negro con detalles dorados.',
    idioma: 'Español',
  },
  {
    id: 'biblia-apuntes-blanco-negro-floral',
    title: 'Biblia de Apuntes Tapa Dura, Blanco/Negro Floral',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 34.24,
    format: 'Tapa dura',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de apuntes con márgenes amplios para anotar, cubierta floral en blanco y negro.',
    idioma: 'Español',
  },
  {
    id: 'biblia-apuntes-azul-oscuro-floral',
    title: 'Biblia de Apuntes Tapa Dura, Azul Oscuro Floral',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 34.2,
    format: 'Tapa dura',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de apuntes con márgenes amplios para anotar, cubierta floral en azul oscuro.',
    idioma: 'Español',
  },
  {
    id: 'biblia-apuntes-azul-celeste-floral',
    title: 'Biblia de Apuntes Tapa Dura, Azul Celeste Floral',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 34.2,
    format: 'Tapa dura',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de apuntes con márgenes amplios para anotar, cubierta floral en azul celeste.',
    idioma: 'Español',
  },
  {
    id: 'biblia-apuntes-rosa-floral',
    title: 'Biblia de Apuntes Tapa Dura, Rosa Floral',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 34.2,
    format: 'Tapa dura',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de apuntes con márgenes amplios para anotar, cubierta floral en tono rosa.',
    idioma: 'Español',
  },
  {
    id: 'biblia-apuntes-vino-tinto',
    title: 'Biblia de Apuntes Tapa Dura, Vino Tinto',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 34.2,
    format: 'Tapa dura',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de apuntes con márgenes amplios para anotar, cubierta lisa en vino tinto.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-cafe',
    title: 'Biblia RVR60 Letra Grande, Café',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 15.24,
    format: 'Tapa dura, imitación piel',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-cafe.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Canto dorado. Cubierta en imitación piel dos tonos grabada, color café.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-verde-mariposas',
    title: 'Biblia RVR60 Letra Grande, Verde Mariposas',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 15.24,
    format: 'Tapa dura, imitación piel',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-verde-mariposas.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Canto dorado. Cubierta en tono verde menta con motivo de mariposas.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-negro',
    title: 'Biblia RVR60 Letra Grande, Negro',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 16.2,
    format: 'Tapa dura, imitación piel',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-negro.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Incluye introducciones y abreviaturas de C.H. Spurgeon y J.C. Ryle, y concordancia de 120 páginas. Cubierta negra con canto dorado.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-marron',
    title: 'Biblia RVR60 Letra Grande, Marrón',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 16.2,
    format: 'Tapa dura, imitación piel',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-marron.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Incluye introducciones y abreviaturas de C.H. Spurgeon y J.C. Ryle, y concordancia de 120 páginas. Cubierta marrón dos tonos con canto dorado.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-beige',
    title: 'Biblia RVR60 Letra Grande, Beige',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 15.24,
    format: 'Tapa dura, imitación piel',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Incluye introducciones y abreviaturas de C.H. Spurgeon y J.C. Ryle, y concordancia de 120 páginas. Cubierta en tono beige.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-amarillo-abejas-cierre',
    title: 'Biblia RVR60 Letra Grande, Amarillo Abejas, con Cierre',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 19.99,
    format: 'Tapa dura, con cierre de cremallera',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-amarillo-abejas-cierre.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Con cierre de cremallera. Cubierta amarilla con motivo de panal y abejas.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-verde-olivo-cierre',
    title: 'Biblia RVR60 Letra Grande, Verde Olivo, con Cierre',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 19.99,
    format: 'Tapa dura, con cierre de cremallera',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-verde-olivo-cierre.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Con cierre de cremallera. Cubierta en tono verde olivo con motivo vegetal.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-marron-elegante-cierre',
    title: 'Biblia RVR60 Letra Grande, Marrón Elegante, con Cierre',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 19.99,
    format: 'Tapa dura, con cierre de cremallera',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-marron-elegante-cierre.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Con cierre de cremallera. Cubierta en dos tonos de marrón.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-cafe-cierre',
    title: 'Biblia RVR60 Letra Grande, Café, con Cierre',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 19.99,
    format: 'Tapa dura, con cierre de cremallera',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-cafe-cierre.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Con cierre de cremallera. Cubierta café con bordes ornamentales grabados.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-beige-floral-cierre',
    title: 'Biblia RVR60 Letra Grande, Beige Floral, con Cierre',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 19.99,
    format: 'Tapa dura, con cierre de cremallera',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-beige-floral-cierre.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Con cierre de cremallera y canto de color. Cubierta beige con motivo de hojas grabado, imitación piel de alta calidad.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-morado-flor-dorada-cierre',
    title: 'Biblia RVR60 Letra Grande, Morado con Flor Dorada, con Cierre',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 19.99,
    format: 'Tapa dura, con cierre de cremallera',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-morado-flor-dorada-cierre.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Con cierre de cremallera. Cubierta morada con motivo floral en dorado y negro.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-rosa-floral-cierre',
    title: 'Biblia RVR60 Letra Grande, Rosa Floral, con Cierre',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 19.99,
    format: 'Tapa dura, con cierre de cremallera',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/portada-proximamente.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Con cierre de cremallera. Cubierta rosa con motivo floral.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-negro-cierre',
    title: 'Biblia RVR60 Letra Grande, Negro, con Cierre',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 19.99,
    format: 'Tapa dura, con cierre de cremallera',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-negro-cierre.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Con cierre de cremallera. Cubierta negra con textura geométrica grabada.',
    idioma: 'Español',
  },
  {
    id: 'biblia-rvr60-aguila-cierre',
    title: 'Biblia RVR60 Letra Grande, Águila, con Cierre',
    author: 'Sociedades Bíblicas Unidas',
    authorSlug: 'sociedades-biblicas-unidas',
    category: 'biblias',
    categoryLabel: 'Biblias',
    price: 19.99,
    format: 'Tapa dura, con cierre de cremallera',
    formatSlug: 'tapa-dura',
    priceNote: 'IVA incluido',
    cover: 'img/biblia-rvr60-aguila-cierre.jpg',
    badge: 'Nuevo',
    description: 'Reina-Valera 1960, edición de letra grande (11,5 puntos), tamaño manual (22 x 15 x 3 cm). Incluye palabras de Jesús en rojo, concordancia amplia, concordancia de personajes bíblicos, referencias cruzadas y 32 páginas a todo color con ayudas de estudio: versículos clave de cada libro, genealogía de Jesús, fiestas bíblicas, plano del templo, cronología de reyes y profetas, parábolas y milagros de Jesús, plan de salvación, promesas de Dios, plan de lectura en un año y 12 mapas a todo color. Con cierre de cremallera. Cubierta marrón grabada con un águila y el texto de Isaías 40:31.',
    idioma: 'Español',
  },
];

// ---- Utilidades compartidas de catálogo -----------------------------------
window.BooksCatalog = {
  getById: function (id) {
    return window.BOOKS.filter(function (b) { return b.id === id; })[0] || null;
  },
  related: function (book, max) {
    max = max || 4;
    return window.BOOKS
      .filter(function (b) { return b.id !== book.id && b.category === book.category; })
      .slice(0, max);
  }
};
